### ISSUE TITLE
Getting this error while decoding

### ISSUE THREAD

**Issue by fzkhan19** [dylanjcastillo/semantic-search-elasticsearch-openai-langchain#2]
(.venv) D:\BeAssured\semantic-search-elasticsearch-openai-langchain>python src/indexer.py
Traceback (most recent call last):
  File "D:\BeAssured\semantic-search-elasticsearch-openai-langchain\src\indexer.py", line 29, in <module>
    main()
  File "D:\BeAssured\semantic-search-elasticsearch-openai-langchain\src\indexer.py", line 11, in main
    data = loader.load()
           ^^^^^^^^^^^^^
  File "D:\BeAssured\semantic-search-elasticsearch-openai-langchain\.venv\Lib\site-packages\langchain\document_loaders\html_bs.py", line 42, in load
    soup = BeautifulSoup(f, **self.bs_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BeAssured\semantic-search-elasticsearch-openai-langchain\.venv\Lib\site-packages\bs4\__init__.py", line 314, in __init__
    markup = markup.read()
             ^^^^^^^^^^^^^
  File "C:\Users\faizk\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 17293: character maps to <undefined>

**Comment by ashishpatel26** [comment]
I got the same error.

```python
(llms) D:\LLMS\SemanticSearch_With_ElasticSearchDB>python indexer.py
Traceback (most recent call last):
  File "D:\LLMS\SemanticSearch_With_ElasticSearchDB\indexer.py", line 29, in <module>
    main()
  File "D:\LLMS\SemanticSearch_With_ElasticSearchDB\indexer.py", line 11, in main
    data = loader.load()
  File "C:\Users\ibm26\.conda\envs\llms\lib\site-packages\langchain\document_loaders\html_bs.py", line 42, in load
    soup = BeautifulSoup(f, **self.bs_kwargs)
  File "C:\Users\ibm26\.conda\envs\llms\lib\site-packages\bs4\__init__.py", line 314, in __init__
    markup = markup.read()
  File "C:\Users\ibm26\.conda\envs\llms\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 17280: character maps to <undefined>
```
